# -*- coding: utf-8 -*-
"""Yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OnBNGJr2cQzRhh8mOY2lyEZ4mZVooh7

- **Split data 8:2**
- **Labeling data menggunakan yolo**
- **strukturnya images/tral|val + labels/train|val dan data.yaml**

Connect ke google drive terlebih dahulu
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!pip -q install ultralytics==8.3.50 pillow tqdm pyyaml

"""Konversi dataset folder-per-kelas → format YOLO (dengan pseudo-bbox dari alpha)"""

import os, random, yaml, shutil
from pathlib import Path
from glob import glob
from PIL import Image
from tqdm import tqdm

random.seed(42)

# === EDIT INI SESUAI PATH DRIVE KAMU ===
# ganti baris SRC kamu jadi:
SRC = Path("/content/drive/MyDrive/COELEGYNE")   # berisi 11 subfolder kelas

# (OUT tetap sama atau sesuai keinginan)
OUT = Path("/content/drive/MyDrive/YOLO/coelogyne_yolo")

VAL_RATIO = 0.2                                               # 8:2

# Bersihkan output bila ada sisa sebelumnya
if OUT.exists():
    shutil.rmtree(OUT)
(OUT / "images" / "train").mkdir(parents=True, exist_ok=True)
(OUT / "images" / "val").mkdir(parents=True, exist_ok=True)
(OUT / "labels" / "train").mkdir(parents=True, exist_ok=True)
(OUT / "labels" / "val").mkdir(parents=True, exist_ok=True)

# Ambil daftar kelas = nama subfolder
classes = sorted([p.name for p in SRC.iterdir() if p.is_dir()])
class_to_id = {c:i for i,c in enumerate(classes)}
print("Kelas terdeteksi:", classes)

def tight_bbox_from_alpha(pil_img):
    """Kembalikan (xmin,ymin,xmax,ymax) berdasarkan alpha channel.
       Jika tak ada alpha/non-zero, fallback seluruh gambar."""
    w, h = pil_img.size
    if pil_img.mode in ("RGBA","LA"):
        alpha = pil_img.split()[-1]
        bbox = alpha.getbbox()  # (l,u,r,b) atau None jika kosong
        if bbox is not None:
            return bbox
    return (0, 0, w, h)

def yolo_normalize(xmin, ymin, xmax, ymax, w, h):
    cx = (xmin + xmax) / 2 / w
    cy = (ymin + ymax) / 2 / h
    bw = (xmax - xmin) / w
    bh = (ymax - ymin) / h
    return cx, cy, bw, bh

# Kumpulkan file per kelas, lalu split PER KELAS (agar distribusi seimbang)
supported = [".png", ".jpg", ".jpeg", ".webp"]
total_train = 0
total_val = 0
skipped = 0

for cls in classes:
    cls_dir = SRC / cls
    files = []
    for ext in supported:
        files += glob(str(cls_dir / f"*{ext}"))
    files = sorted(files)
    random.shuffle(files)

    n_val = max(1, int(len(files) * VAL_RATIO))  # jaga-jaga minimal 1
    val_files = set(files[:n_val])
    train_files = files[n_val:]

    for f in tqdm(files, desc=f"[{cls}]"):
        split = "val" if f in val_files else "train"
        try:
            img = Image.open(f)
            # Pastikan ada channel untuk alpha check
            if img.mode not in ("RGBA","LA"):
                # Untuk JPG tanpa alpha, konversi ke RGBA agar mudah, alpha akan full-opaque
                img = img.convert("RGBA")
            w, h = img.size
            xmin, ymin, xmax, ymax = tight_bbox_from_alpha(img)
            xmin, ymin = max(0, xmin), max(0, ymin)
            xmax, ymax = min(w, xmax), min(h, ymax)
            if xmax <= xmin or ymax <= ymin:
                skipped += 1
                continue

            cx, cy, bw, bh = yolo_normalize(xmin, ymin, xmax, ymax, w, h)
            cls_id = class_to_id[cls]

            # Salin gambar
            dst_img = OUT / "images" / split / Path(f).name
            shutil.copy2(f, dst_img)

            # Tulis label
            dst_lbl = OUT / "labels" / split / (Path(f).stem + ".txt")
            with open(dst_lbl, "w") as lf:
                lf.write(f"{cls_id} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}\n")

            if split == "train": total_train += 1
            else: total_val += 1

        except Exception as e:
            skipped += 1
            print("Skip (error):", f, "->", e)

# Tulis data.yaml
data_yaml = {
    "path": str(OUT),
    "train": "images/train",
    "val": "images/val",
    "nc": len(classes),
    "names": classes
}
with open(OUT / "data.yaml", "w") as yf:
    yaml.safe_dump(data_yaml, yf, sort_keys=False, allow_unicode=True)

print(f"Selesai. Train: {total_train}, Val: {total_val}, Skipped: {skipped}")
print("data.yaml:", OUT / "data.yaml")

"""Cek salah satu contoh"""

# Tampilkan satu contoh label dari set val
sample_lbls = list((OUT / "labels" / "val").glob("*.txt"))
print("Contoh label:", sample_lbls[:3])
if sample_lbls:
    print(open(sample_lbls[0]).read())

"""Train yolov8"""

!pip -q install -U ultralytics==8.3.221

import torch, os
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    # kalau sebelumnya sempat set env ini, kosongkan
    os.environ.pop("CUDA_VISIBLE_DEVICES", None)

from ultralytics import YOLO
model = YOLO('yolov8n.pt')

results = model.train(
    data=str(OUT / "data.yaml"),
    imgsz=640,
    epochs=20,         # batas maksimum
    patience=5,        # early stop kalau 20 epoch tak membaik
    batch=16,
    name="coelogyne_det_alpha",
    pretrained=True     # biarkan otomatis pilih device
)

"""Eval validation"""

from ultralytics import YOLO

# pakai weight terbaik dari training tadi
best = "/content/runs/detect/coelogyne_det_alpha/weights/best.pt"
model = YOLO(best)

metrics = model.val(data=str(OUT / "data.yaml"), imgsz=640, conf=0.25)
print(metrics)  # ringkasan mAP50, mAP50-95, precision, recall



"""Testing"""

from ultralytics import YOLO
from IPython.display import Image, display
import glob, os

best = "/content/runs/detect/coelogyne_det_alpha/weights/best.pt"  # ganti kalau beda
model = YOLO(best)

# Cek metrik val
metrics = model.val(data=str(OUT / "data.yaml"), imgsz=640, conf=0.25)
print(metrics)

# Ambil 1 contoh gambar dari set val lalu predict
val_imgs = glob.glob(str(OUT / "images" / "val" / "*"))
if val_imgs:
    sample = val_imgs[0]
    print("Sample val image:", sample)
    pred = model.predict(source=sample, imgsz=640, conf=0.05, save=True,
                         project="/content/preds", name="val_sample", exist_ok=True)
    print("Saved to:", pred[0].save_dir)
    # tampilkan
    for p in glob.glob(os.path.join(pred[0].save_dir, "*")):
        if p.lower().endswith((".png",".jpg",".jpeg",".webp")):
            display(Image(filename=p))

from google.colab import files
from ultralytics import YOLO
from IPython.display import Image, display
import os, glob

# 1) Upload file
uploaded = files.upload()

# 2) Load weight (pastikan path-nya sesuai run kamu)
best = "/content/runs/detect/coelogyne_det_alpha/weights/best.pt"
model = YOLO(best)
print("Class names in model:", model.names)

OUT_DIR = "/content/preds"
RUN_NAME = "uploaded_retry_no_tta"
save_dir = None

# 3) Predict dengan threshold longgar & resolusi lebih besar
for fname in uploaded.keys():
    print(f"\n=== Predicting {fname} ===")
    preds = model.predict(
        source=fname,
        imgsz=896,      # naikkan resolusi
        conf=0.001,      # lebih longgar
        iou=0.6,
        max_det=3,
        save=True,
        save_txt=True,
        project=OUT_DIR,
        name=RUN_NAME,
        exist_ok=True,
        verbose=False
    )
    res = preds[0]
    save_dir = res.save_dir

    # Ringkasan deteksi
    if res.boxes is None or len(res.boxes) == 0:
        print(">> NO DETECTIONS. Coba turunkan conf lagi (mis. 0.001) atau cek langkah perbaikan training.")
    else:
        for b in res.boxes:
            cls_id = int(b.cls.item())
            conf = float(b.conf.item())
            xyxy = [round(float(x),1) for x in b.xyxy[0].tolist()]
            print(f">> Det: {model.names.get(cls_id, cls_id)}  conf={conf:.3f}  box={xyxy}")

# 4) Tampilkan gambar hasil anotasi
if save_dir and os.path.isdir(save_dir):
    print("\nHasil tersimpan di:", save_dir)
    for p in glob.glob(os.path.join(save_dir, "*")):
        if p.lower().endswith((".png",".jpg",".jpeg",".webp")):
            display(Image(filename=p))
else:
    print("Tidak menemukan folder output. Cek nilai project/name.")

"""Diperkecil"""

# === LOAD MODEL & SET PATH ===
from ultralytics import YOLO
from IPython.display import Image as IPyImage, display
from PIL import Image
import os, glob, math

# ganti ke path best.pt kamu
best = "/content/runs/detect/coelogyne_det_alpha/weights/best.pt"
model = YOLO(best)
print("Class names:", model.names)

# folder output untuk hasil predict
OUT_DIR = "/content/preds"

from google.colab import files
from PIL import Image

uploaded = files.upload()  # pilih satu/lebih gambar

def shrink_box(xyxy, shrink_ratio, W, H):
    """xyxy: [x1,y1,x2,y2], shrink_ratio: 0.0-0.4 umum, W,H: ukuran gambar"""
    x1, y1, x2, y2 = xyxy
    w = x2 - x1
    h = y2 - y1
    dx = w * shrink_ratio
    dy = h * shrink_ratio
    nx1 = max(0, x1 + dx)
    ny1 = max(0, y1 + dy)
    nx2 = min(W, x2 - dx)
    ny2 = min(H, y2 - dy)
    if nx2 <= nx1 or ny2 <= ny1:  # fallback kalau terlalu kecil
        return [x1, y1, x2, y2]
    return [nx1, ny1, nx2, ny2]

SHRINK = 0.10   # 10% tiap sisi; ubah ke 0.05/0.2 sesuai selera
CONF   = 0.01   # longgarkan kalau sering “no detections”
IMGSZ  = 896    # naikkan untuk objek kecil

save_dir = None
for fname in uploaded.keys():
    print(f"\n=== Predict {fname} ===")
    preds = model.predict(
        source=fname, imgsz=IMGSZ, conf=CONF, iou=0.6,
        save=True, save_txt=True, project=OUT_DIR, name="shrink_box", exist_ok=True, verbose=False
    )
    res = preds[0]
    save_dir = res.save_dir

    # buka gambar asli untuk crop manual
    im = Image.open(fname).convert("RGB")
    W, H = im.size

    if res.boxes is None or len(res.boxes) == 0:
        print(">> NO DETECTIONS (coba turunkan conf atau perbesar imgsz).")
        continue

    # proses tiap deteksi → crop yang sudah dikecilkan
    for i, b in enumerate(res.boxes):
        cls_id = int(b.cls.item())
        conf = float(b.conf.item())
        x1, y1, x2, y2 = [float(x) for x in b.xyxy[0].tolist()]
        tight = shrink_box([x1, y1, x2, y2], SHRINK, W, H)

        cx1, cy1, cx2, cy2 = [int(round(v)) for v in tight]
        crop = im.crop((cx1, cy1, cx2, cy2))
        crop_path = os.path.join(save_dir, f"{os.path.splitext(os.path.basename(fname))[0]}_crop{i}_{model.names[cls_id]}_{conf:.2f}.jpg")
        crop.save(crop_path, quality=95)

        print(f">> Det{i}: {model.names[cls_id]} conf={conf:.3f} box={list(map(lambda z: round(z,1), [x1,y1,x2,y2]))} -> shrink → {cx1,cy1,cx2,cy2}")
        display(IPyImage(filename=crop_path))

print("\nGambar dengan bbox overlay + crop tersimpan di:", save_dir)

from google.colab import files
from PIL import Image
import uuid

uploaded = files.upload()

# ROI preset: ambil bagian tengah 60% lebar & tinggi
ROI_CENTER_FRACTION = 0.60   # ubah 0.5–0.8 sesuai kebutuhan
CONF   = 0.001
IMGSZ  = 896

def crop_center_roi(src_path, frac=0.6):
    im = Image.open(src_path).convert("RGB")
    W, H = im.size
    w = int(W * frac)
    h = int(H * frac)
    x1 = (W - w) // 2
    y1 = (H - h) // 2
    x2 = x1 + w
    y2 = y1 + h
    roi = im.crop((x1, y1, x2, y2))
    # simpan sementara
    tmp_path = f"/content/tmp_roi_{uuid.uuid4().hex}.jpg"
    roi.save(tmp_path, quality=95)
    return tmp_path, (x1, y1, x2, y2), (W, H)

save_dir = None
for fname in uploaded.keys():
    print(f"\n=== ROI Predict {fname} ===")
    roi_path, roi_xyxy, orig_size = crop_center_roi(fname, ROI_CENTER_FRACTION)
    preds = model.predict(
        source=roi_path, imgsz=IMGSZ, conf=CONF, iou=0.6,
        save=True, save_txt=True, project=OUT_DIR, name="roi_only", exist_ok=True, verbose=False
    )
    res = preds[0]
    save_dir = res.save_dir

    if res.boxes is None or len(res.boxes) == 0:
        print(">> NO DETECTIONS pada ROI. Coba ubah ROI_CENTER_FRACTION (mis. 0.8) atau pakai full image.")
    else:
        for i, b in enumerate(res.boxes):
            cls_id = int(b.cls.item())
            conf = float(b.conf.item())
            print(f">> Det{i} di ROI: {model.names.get(cls_id, cls_id)} conf={conf:.3f}")

    # tampilkan hasil anotasi yang disimpan Ultralytics
    for p in glob.glob(os.path.join(save_dir, "*")):
        if p.lower().endswith((".png", ".jpg", ".jpeg", ".webp")):
            display(IPyImage(filename=p))

print("\nHasil ROI inference tersimpan di:", save_dir)